{% set name = "dtale" %}
{% set version = "1.23.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5afe35d1abb5d22a8ba61fb9df963b516bfe65ea0c07ceedf5974280c304c7dd

build:
  number: 0 
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - dtale = dtale.cli.script:main

requirements:
  host:
    - python
    - pip
    - six
  run:
    - python
    - lz4
    - dash
    - dash-bootstrap-components
    - dash_colorscales
    - dash-daq
    - Flask-Compress
    - Flask
    - future
    - itsdangerous
    - pandas
    - requests
    - scikit-learn
    - scipy
    - six
    - squarify
    - statsmodels
    - strsimpy
    - xarray

test:
  commands:
    - dtale --help
  imports:
    - dtale
    - dtale.cli

about:
  home: https://github.com/man-group/dtale/
  license: LGPL-2.1-only
  license_file: LICENSE
  summary: D-Tale is the combination of a Flask back-end and a React front-end to bring you an easy way to view & analyze Pandas data structures

  doc_url: https://dtale.readthedocs.io
  dev_url: https://github.com/man-group/dtale/

extra:
  recipe-maintainers:
    - aschonfeld
